<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net462;net10.0-windows</TargetFrameworks>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>

    <Company>Junian.dev</Company>
    <Product>WinForms Demo</Product>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="SUFeedURL" Value="https://sparkle-project.org/files/sparkletestcast.xml" />
    <AssemblyMetadata Include="SUPublicEDKey" Value="pfIShU4dEXqPd5ObYNfDBiQWcXozk7estwzTnF9BamQ=" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\..\UpSparkle\UpSparkle.csproj" />
  </ItemGroup>

</Project>