<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-macos</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>12.0</SupportedOSPlatformVersion>

    <!--
      Enable full trimming in Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
    <TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>

    <Company>Junian.dev</Company>
    <Product>.NET macOS Demo</Product>
    <Version>0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <AssemblyMetadata Include="SUFeedURL" Value="https://sparkle-project.org/files/sparkletestcast.xml" />
    <AssemblyMetadata Include="SUPublicEDKey" Value="pfIShU4dEXqPd5ObYNfDBiQWcXozk7estwzTnF9BamQ=" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\UpSparkle\UpSparkle.csproj" />
  </ItemGroup>
</Project>
