<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;</TargetFrameworks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>true</IsPackable>
    <RootNamespace>UpSparkle</RootNamespace>
    <AssemblyName>UpSparkle</AssemblyName>
    <Authors>Junian Triajianto</Authors>
    <NeutralLanguage>en</NeutralLanguage>
    <Owners>junian</Owners>
    <PackageProjectUrl>https://www.junian.dev/upsparkle/</PackageProjectUrl>
    <PackageReleaseNotes>$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)/../../ReleaseNotes.txt"))</PackageReleaseNotes>
    <Summary>$(Description)</Summary>
    <PackageTags>sparkle,winsparkle,updater,macos,maccatalys,windows</PackageTags>
    <Title>UpSparkle</Title>
    <Description>Easy-to-use licensing library for .NET and .NET Framework products.</Description>
    <PackageId>UpSparkle</PackageId>
    <Copyright>Copyright (c) 2026</Copyright>
    <RepositoryUrl>https://github.com/junian/upsparkle</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <!--
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>Standard.Licensing.snk</AssemblyOriginatorKeyFile>
    -->
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <!--
    <PackageIcon>standard-licensing-logo.png</PackageIcon>
    -->
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <CLSCompliant>True</CLSCompliant>
    
    <!-- Versions -->
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <ReleaseVersion>$(AssemblyVersion)</ReleaseVersion>
    <Version>$(AssemblyVersion)</Version>
    <FileVersion>$(AssemblyVersion)</FileVersion>
  </PropertyGroup>
	
  <ItemGroup>
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
    <None Include="..\..\docs\README.md" Pack="true" PackagePath="\" />
    <!--
    <None Include="..\..\assets\img\standard-licensing-logo.png" Pack="true" PackagePath="\" />
    -->
  </ItemGroup>

  <!-- Expose Internals to Tests -->
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>UpSparkle.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <!-- Sparkle.framework (macOS) -->
  <ItemGroup>
    <None Include="..\..\runtimes\osx\native\Sparkle.framework\**"
          Pack="true"
          PackagePath="runtimes/osx/native/Sparkle.framework/%(RecursiveDir)%(Filename)%(Extension)">
      <Link>runtimes\osx\native\Sparkle.framework\%(RecursiveDir)%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\runtimes\osx\native\libMacSparkle.dylib"
          Pack="true"
          PackagePath="runtimes/osx/native/libMacSparkle.dylib">
      <Link>runtimes\osx\native\libMacSparkle.dylib</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- WinSparkle (Windows) -->
  <ItemGroup>
    <None Include="..\..\runtimes\win-x86\native\WinSparkle.dll"
          Pack="true"
          PackagePath="runtimes/win-x86/native/WinSparkle.dll">
      <Link>runtimes\win-x86\native\WinSparkle.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\runtimes\win-x64\native\WinSparkle.dll"
          Pack="true"
          PackagePath="runtimes/win-x64/native/WinSparkle.dll">
      <Link>runtimes\win-x64\native\WinSparkle.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\runtimes\win-arm64\native\WinSparkle.dll"
          Pack="true"
          PackagePath="runtimes/win-arm64/native/WinSparkle.dll">
      <Link>runtimes\win-arm64\native\WinSparkle.dll</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
